export const PREDEFINED_CATEGORIES = [
  'Work',
  'Personal',
  'Family',
  'Health',
  'Fitness',
  'Nutrition',
  'Study',
  'Reading',
  'Finance',
  'Shopping',
  'Housework',
  'Home Maintenance',
  'Car / Vehicle',
  'Documents',
  'Meetings',
  'Calls',
  'Email',
  'Project A',
  'Project B',
  'Long-term Goals',
  'Daily Routines',
  'Travel / Trips',
  'Hobbies',
  'Creative',
  'Courses / Learning',
  'Career & Growth',
  'Networking / Contacts',
  'Mindfulness / Mental Health',
  'Sleep / Schedule',
  'Day Planning',
  'Week Planning',
  'Month Planning',
  'Legal',
  'Banking / Payments',
  'Subscriptions / Renewals',
  'Tech / Devices',
  'Cleaning / Organization',
  'Pets',
  'Gifts / Events',
  'Online Orders / Deliveries',
  'Notes / Ideas',
  'Side Projects',
  'Content / Social Media',
  'Languages / Practice',
  'Music / Instruments',
  'Sports / Games to Watch',
  'Medical / Doctors / Tests',
  'Car Service / Insurance / Taxes',
  'Entertainment / Movies / Series',
  'Important but Not Urgent',
] as const;

export type PredefinedCategory = (typeof PREDEFINED_CATEGORIES)[number];
